services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline-pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pipeline -d challenge" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RECIPE_URL: ${RECIPE_URL}
      POSTGRES_URL: ${POSTGRES_URL}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    working_dir: /app/src
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "whats_for_dinner.app:app",
        "--reload",
      ]
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    depends_on:
      db:
        condition: service_healthy
